<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fef388b9-e1db-4866-81cd-fb3a86884d2e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="App.scss" />
    <None Remove="Kori\Guide.scss" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="App.scss">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="App.Typography.scss" />
    <Content Include="App.Variables.scss" />
    <Content Include="Kori\KoriWidget.scss" />
    <Content Include="Pages\Guide.scss" />
    <Content Include="Shared\NavMenu.scss" />
	<Content Include="Shared\Footer.scss" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
    <None Include="wwwroot\kori\borders\black-16.svg" />
    <None Include="wwwroot\kori\borders\black-8.svg" />
    <None Include="wwwroot\kori\borders\Box_4 with carrot.svg" />
    <None Include="wwwroot\kori\borders\orange-16.svg" />
    <None Include="wwwroot\kori\icons\Attachment.svg" />
    <None Include="wwwroot\kori\icons\Bold.svg" />
    <None Include="wwwroot\kori\icons\Bullet.svg" />
    <None Include="wwwroot\kori\icons\Code.svg" />
    <None Include="wwwroot\kori\icons\Italic.svg" />
    <None Include="wwwroot\kori\icons\Link.svg" />
    <None Include="wwwroot\kori\icons\Numbered.svg" />
    <None Include="wwwroot\kori\icons\Quote.svg" />
    <None Include="wwwroot\kori\icons\Strikethrough.svg" />
    <None Include="wwwroot\kori\icons\Union.svg" />
    <None Include="wwwroot\kori\icons\User.svg" />
    <None Include="wwwroot\kori\images\dock-icon.svg" />
    <None Include="wwwroot\kori\images\kori-buddy.svg" />
    <None Include="wwwroot\kori\js\kori.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="7.0.0" />
    <PackageReference Include="Sparc.Ibis" Version="7.0.5" />
    <PackageReference Include="Sparc.Kernel" Version="7.0.0" />
  </ItemGroup>

</Project>